// Code generated by goctl. DO NOT EDIT.
package types

type UserFile struct {
	Id                 int64  `json:"id"`
	ParentId           int64  `json:"parentId";xorm:"parent_id"`
	Type               string `json:"type"`
	Name               string `json:"name"`
	RepositoryIdentity string `json:"repositoryIdentity"`
	Identity           string `json:"identity"`
	Ext                string `json:"ext"`
	Path               string `json:"path"`
}

type Result struct {
	Code    int         `json:"code"`
	Data    interface{} `json:"data"`
	Message string      `json:"message"`
}

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Result
}

type RegisterRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type RegisterResponse struct {
	Result
}

type GetCodeRequest struct {
	Email string `form:"email"` //用户邮箱
}

type GetCodeResponse struct {
	Result
}

type UserInfoRequest struct {
}

type UserInfoResponse struct {
	Result
}

type UploadFileRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type UploadFileResponse struct {
	Result
}

type UserRepositoryLinkRequest struct {
	ParentId           int64  `json:"parentId"`
	RepositoryIdentity string `json:"repositoryIdentity"`
	Ext                string `json:"ext"`
	Name               string `json:"name"`
	Type               string `json:"type"`
}

type UserRepositoryLinkResponse struct {
	Result
}

type UserFileListRequest struct {
	Id   int64 `form:"id,optional"`
	Page int   `form:"page"`
	Size int   `form:"size"`
}

type UserFileListResponse struct {
	Result
}

type UserFileNameEditRequest struct {
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type UserFileNameEditResponse struct {
	Result
}

type UserDirCreateRequest struct {
	ParentId int64  `json:"parentId"`
	Name     string `json:"name"`
}

type UserDirCreateResponse struct {
	Result
}

type UserDeleteFileRequest struct {
	Identity string `json:"identity,optional";form:"identity"`
}

type UserDeleteFileResponse struct {
	Result
}

type UserFileMovedRequest struct {
	Identity       string `json:"identity"`
	ParentIdentity string `json:"parentIdentity"`
}

type UserFileMovedResponse struct {
	Result
}

type ShareBasicCreateRequest struct {
	UserRepositoryIdentity string `json:"userRepositoryIdentity"`
	ExpiredTime            int64  `json:"expiredTime"`
}

type ShareBasicCreateResponse struct {
	Result
}

type ShareBasicDetailRequest struct {
	Identity string `json:"identity"`
}

type ShareBasicDetailResponse struct {
	Result
}

type ShareBasicSaveRequest struct {
	RepositoryIdentity string `json:"repositoryIdentity"`
	ParentId           int64  `json:"parentId"`
}

type ShareBasicSaveResponse struct {
	Result
}

type RefreshAuthorizationResponse struct {
	Result
}

type GetUserRepostoryByIdRequest struct {
	Id int `form:"id"`
}

type GetUserRepostoryByIdResponse struct {
	Result
}
